### ISSUE TITLE
template // cannot start server

### ISSUE THREAD

**Issue by Adeynack** [nerdgeschoss/development-environment#7]
Template created project won't start. `bin/rails s` produces this error.

```
[WARNING] Could not load command "rails/commands/server/server_command". Error: Rails::Engine is abstract, you cannot instantiate it directly..
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/railtie.rb:246:in `initialize'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/railtie.rb:184:in `new'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/railtie.rb:184:in `instance'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/railtie.rb:223:in `method_missing'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.0/lib/active_support/descendants_tracker.rb:90:in `descendants'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:923:in `block in define_callbacks'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:920:in `each'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:920:in `define_callbacks'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/engine.rb:427:in `<class:Engine>'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/engine.rb:349:in `<module:Rails>'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/engine.rb:11:in `<main>'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/application.rb:11:in `<main>'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails.rb:13:in `<main>'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/commands/server/server_command.rb:5:in `<main>'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/command/behavior.rb:40:in `each'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/command/behavior.rb:40:in `block in lookup'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/command/behavior.rb:39:in `each'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/command/behavior.rb:39:in `lookup'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/command.rb:73:in `find_by_namespace'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/command.rb:46:in `invoke'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/commands.rb:18:in `<main>'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/adeynack/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
rails aborted!
Rails::Engine is abstract, you cannot instantiate it directly.
/Users/adeynack/src/config/application.rb:3:in `<main>'
/Users/adeynack/src/Rakefile:4:in `require_relative'
/Users/adeynack/src/Rakefile:4:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

**Comment by Adeynack** [comment]
Updating to `gem 'rails', '~> 7.0.2'` solved. it.
The template should reflect that.
